### ISSUE TITLE
unit test LoadMoreButton component from within CardGrid component

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#106]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

As originaly reported [here](https://github.com/ProvidenceGeeks/website-frontend/pull/101#issuecomment-349038394)

### Overview
So essentially where I'm stuck is trying to simulate a click event [here](https://github.com/ProvidenceGeeks/website-frontend/blob/technical/issue-99-reusable-grid/src/components/card-grid/card-grid.jsx#L65)
I have a `LoadMoreButton` component nested in the `CardGrid` component
```javascript
render() {
  return (
    <div>
      /* CardGrid Stuff */
  
      <div>
      {
        this.state.canLoadMore
          ? <LoadMoreButton loadMore={ () => this.loadMoreItems() }/>
          : ''
      }
      </div>
    </div>
  )
}
```

[In this spec](https://github.com/ProvidenceGeeks/website-frontend/blob/develop/src/components/card-grid/card-grid.spec.jsx#L109), I provide a `data` array of 12 items.  The `CardGrid` shows 6 `Card` components per page.  So with this setup
1.  The `CardGrid` component should show the `LoadMoreButton` component and 6 cards
2.  When the button is clicked, 12 `Card` components should show
```javascript
describe('CardGrid component when initial data.length prop is 2 pages and loadMore is clicked ', () => {
  let expected;
  let cardGrid;

  beforeEach(() => {
    expected = defaultItemsPerPage * 2;
    let data = getMockData(expected);
    cardGrid = mount(<CardGrid data={data}/>);
  });

  it(`should show ${defaultItemsPerPage} Card components before LoadMoreButton is clicked`, () => {
    expect(cardGrid.find(Card).length).toEqual(defaultItemsPerPage);
  });

  it(`should show the LoadMoreButton component when data.length prop is ${defaultItemsPerPage * 2}`, () => {
    expect(cardGrid.find(LoadMoreButton).length).toEqual(1);
  });
  
  it(`should show ${expected} Card components when data.length prop is ${expected} and LoadMoreButton is clicked once`, () => {
    cardGrid.find(LoadMoreButton).simulate('click');

    expect(cardGrid.find(Card).length).toEqual(expected);  // length is still 6 🤔 
  });
});
```

### Analysis
I think there is a known issue with propagating events with enzyme?
https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/simulate.md#common-gotchas

### Extra Credit
1. I don't think `currentPage` is used, it can probably be removed from `this.state`
1. Consider bumping up jest coverage thresholds once this lands
1. Instead of using template literals in the the `it` blocks, it may be preferable to "hardcode" the expected values

**Comment by paul-barry-kenzan** [comment]
Extra Credit Response

> 1. I don't think currentPage is used, it can probably be removed from this.state
Agreed, if it's not being used, cut it. Bloat causes confusion and git can be used to restore past features or logic.

> 2. Consider bumping up jest coverage thresholds once this lands
I'm in favor of always staying accountable for the work and tests added, so increasing thresholds are a great way to keep the team writing tests. They do tend to be a cause of headaches during refactors, but again, keeps devs aware of the missing lines.  

> 3. Instead of using template literals in the the it blocks, it may be preferable to "hardcode" the expected values
The spec description should be considered sacred. It's describing to everyone who cares, exactly what this particular piece of code is doing. And in doing so, build confidence in the development team and in the application stability. By having a vague description, you're loosening that confidence. 

When it comes to dynamic tests, including description construction, I say use sparingly. Constant values are usually ok with me since they are meant to be a single declaration/multiple use. Having counts and such based on array lengths is usually ok with me, however, I tend to phrase the description in a way that describes that the lengths should be equal without using digits directly.

I've become really picky with my descriptions and certainly know that they are my preference and not any type of golden rule. I should start a gist or something.....

**Comment by thescientist13** [comment]
Hit me up with that gist if you make it @paul-barry-kenzan !

**Comment by thescientist13** [comment]
@saimatsumoto 
This should be technical change and so all behaviors with Events and Blog Posts lists should behave as normal.

**Comment by saimatsumoto** [comment]
Validated that Events List and Blog Posts behavior have not changed and functions as expected other than the known issues:

* page responsiveness: https://github.com/ProvidenceGeeks/website-frontend/issues/65
* Post-list card styling: https://github.com/ProvidenceGeeks/website-frontend/issues/102
* Post images don't load initially: https://github.com/ProvidenceGeeks/website-frontend/issues/111
