### ISSUE TITLE
Improve accessibility score of the application

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#145]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

Apply suggested feedback from Lighthouse for Accessibility 
<img width="782" alt="screen shot 2018-04-03 at 11 00 12 am" src="https://user-images.githubusercontent.com/895923/38258754-48c6a738-3731-11e8-80d6-ed8bcb780b9a.png">

**Comment by DevLab2425** [comment]
As of Oct 18, 2019
![Screen Shot 2019-10-18 at 11 47 44 PM](https://user-images.githubusercontent.com/8385375/67137358-c5dd1400-f201-11e9-9f1b-6d6180ac7dbe.png)

**Comment by DevLab2425** [comment]
@thescientist13 
This has to be reopened, or at least a new issue. When #189 was merged, it causes the Blog Post content to be removed from the DOM on the initial load. This then causes an accessibility error because the Blog Post button is trying to reference an element ID that doesn't technically exist (yet).

**From staging on 10/30/19**
![Screen Shot 2019-10-30 at 8 31 53 PM](https://user-images.githubusercontent.com/8385375/67909088-601f4f00-fb54-11e9-9a27-22e5457534eb.png)

**Comment by thescientist13** [comment]
@DevLab2425 
Do you mind filling a new issue and linking to this one?

**Comment by thescientist13** [comment]
@DevLab2425 
Actually, this change is still in stage.pvdgeeks.org, so we can jus reopen if you think it's a quick enough fix.  Otherwise, a new issue is fine with me.  Your call.
