### ISSUE TITLE
Include GitHub icon with social links

### ISSUE THREAD

**Issue by DevLab2425** [ProvidenceGeeks/website-frontend#169]
## Type of Change
- [x] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

Add an additional icon to the social list and link to the GitHub organization. 

Link should be:

- GitHub icon in the style of the current icons
- Linked to, in a new window: https://github.com/ProvidenceGeeks/
- Listed last in the list

**Comment by thescientist13** [comment]
Great idea @DevLab2425 !

**Comment by tmelliottjr** [comment]
I'd like to tackle this one. 

Is there a particular source that is being used for the icons? Looking at the official [icons](https://github.com/logos) there doesn't appear to be a similar style available. There are other sources of course, but I wanted to be sure.

**Comment by thescientist13** [comment]
Hey @tmelliottjr , thanks for checking this issue out, would be great to have a contribution for this!

As far as icon source, we've been using `<svg>` for the icons in this application.  You can example of one for the `FacebookIcon` component.
https://github.com/ProvidenceGeeks/website-frontend/blob/develop/src/components/facebook-icon/facebook-icon.jsx

I think the "mark" version would be good.  I downloaded the pack and it doesn't include an svg version, so we might have to grab it from [google](https://www.google.com/search?rlz=1C5CHFA_enUS758US758&tbm=isch&q=github+logo&chips=q:github+logo,g_1:svg:I1OsEo0GNUo%3D&usg=AI4_-kSGJNGCGo5WOIMho1ru-js3UATdiA&sa=X&ved=0ahUKEwjy3rKFmeTgAhUPSN8KHcCtChYQ4lYIKigB&biw=1493&bih=816&dpr=2.2).  

Since an .svg is just text, if you open the file in a browser and `view:source` you should see the `<svg>` content that you can use in the JSX of a `GitHubIcon` component.

Let me know if you have any questions.  👍

**Comment by tmelliottjr** [comment]
I didn't articulate that clearly, sorry. I meant where I 'should' grab the SVG from. For example, [flaticon](https://www.flaticon.com/free-icon/github-sign_25657) or the like. 

I wanted to make sure I used one with a consistent look and feel (rounded borders with the logo inside) and the flaticon version has a slightly different border-radius. 

After looking at the icons currently in use, perhaps that isn't an issue. I have something ready to go, I'll submit a PR shortly.

**Comment by thescientist13** [comment]
ah, I see what you mean.  

yeah, I would say use your best judgement and just use the one you find that best matches the shape / style / size as the others.

If you can share a screenshot in the PR, we can review that, and then I'm sure this would be good to go.  👌

**Comment by thescientist13** [comment]
Up on stage
http://stage.pvdgeeks.org/
